### ISSUE TITLE
Update tests in releaser/git_test.go 

### ISSUE THREAD

**Issue by mibragimchayev** [gothamhq/gotham#14]
Update all tests in [releaser/git_test.go](https://github.com/gothamhq/gotham/blob/7bff50435d4980c3a872d858a1754212701c2280/releaser/git_test.go) to reference Gotham tags and issues.

The current tests fail when running `mage -v test` locally

**Comment by felicianotech** [comment]
@mibragimchayev This was completed right?

**Comment by mibragimchayev** [comment]
yes! good catch. Looks like we had two separate issues that were similar.
