### ISSUE TITLE
Gotham Version should not have commit hash

### ISSUE THREAD

**Issue by chayev** [gothamhq/gotham#189]

**Comment by chayev** [comment]
It looks like this started between released v0.6.0 and v0.7.0

Still trying to pinpoint what caused it. @felicianotech any ideas?

**Comment by felicianotech** [comment]
GoReleaser didn't inject the hash like it was suppose to. When we fixed that, the code [here](https://github.com/gothamhq/gotham/blob/ac560db62dfe8e932f860bad9658ad380215f8ec/src/common/hugo/semver-version.go#L49) prints it. It needs logic to only do that for dev releases, not on production ones.
