### ISSUE TITLE
Warning when using go run on Mac

### ISSUE THREAD

**Issue by mibragimchayev** [gothamhq/gotham#35]
Using Mac Version 10.15.4

When trying to use `go run .` 

I tried using the `version` and `help` commands

Error below:

```
# github.com/bep/golibsass/internal/libsass
In file included from inspect.cpp:2:
../../../../go/pkg/mod/github.com/bep/golibsass@v0.6.0/internal/libsass/../../libsass_src/src/inspect.cpp:1069:20: warning: expression with side effects will be evaluated despite being used as an operand to 'typeid' [-Wpotentially-evaluated-expression]
```

**Comment by mibragimchayev** [comment]
This is happening in CircleCI as well for Mac during the [mage check step](https://app.circleci.com/pipelines/github/gothamhq/gotham/160/workflows/5a8da74e-ebf9-4292-9096-316e5e262c72/jobs/231/parallel-runs/0/steps/0-108)

**Comment by felicianotech** [comment]
Renaming this as this is a warning not an error.

**Comment by mibragimchayev** [comment]
This warning is not specific to our project. 
Opened an issue in the libsass project: https://github.com/sass/libsass/issues/3113
