### ISSUE TITLE
The meta generator tag is still Hugo on a built site

### ISSUE THREAD

**Issue by felicianotech** [gothamhq/gotham#56]
The meta generator tag is still Hugo when using `gotham` as opposed to `gotham serve`.

**Comment by felicianotech** [comment]
Some info:

I built Feliciano.Tech locally (gotham not gotham serve) and the tag was Hugo. The Reserve Force (TRF), both the production and staging sites say Hugo.

The Gotham launch site says Gotham.

One of the only changes I can think of right now is that the launch site source is in the root directory where for Feliciano.Tech and TRF are in an `src` subdirectory.

**Comment by felicianotech** [comment]
@mibragimchayev Let me know when you're working on this. I have more info but I don't know if you wanna discover it yourself or not.

**Comment by mibragimchayev** [comment]
Updated code and tests on Feliciano.Tech locally, and meta tag now is correct.

https://github.com/gothamhq/gotham/tree/meta-tag-gen-v2

The tests still need to be updated.
