### ISSUE TITLE
The Built-In Browser Error Screen Uses Hugo's version

### ISSUE THREAD

**Issue by felicianotech** [gothamhq/gotham#61]
The built-in error system that Gotham uses in the browser is still reports the Hugo version number.

![FireShot Capture 042 - Hugo Server_ Error - localhost](https://user-images.githubusercontent.com/6017470/85236193-a24e1700-b3e9-11ea-8f77-7ce4f15c67ac.png)

**Comment by mibragimchayev** [comment]
I believe this is due to line 133 in [.common/hugo/version.go](https://github.com/gothamhq/gotham/blob/89ef6c4260d18ee9f662fcd299e784b624ee860b/common/hugo/version.go)

@felicianotech how could I recreate this error message?

**Comment by felicianotech** [comment]
@mibragimchayev Mess something up. For example, in the launch site, go to the homepage template file and mispell the `template` tag as `teeemplate`. The file can be found here: `themes/hugo-theme-lean-launch-page/layouts/index.html`

**Comment by felicianotech** [comment]
Btw, I don't think that line/file is the problem. Is the line/file that's calling it.
