### ISSUE TITLE
CircleCI: Extend default step timeout past 10 minutes

### ISSUE THREAD

**Issue by mibragimchayev** [gothamhq/gotham#67]
See below error [here](https://app.circleci.com/pipelines/github/gothamhq/gotham/237/workflows/7e97c31f-f00a-40f0-9e78-567c4a5ab5fb/jobs/506) 

`Too long with no output (exceeded 10m0s): context deadline exceeded`

**Comment by felicianotech** [comment]
@mibragimchayev I don't think we need to do this anymore. Thoughts?

**Comment by mibragimchayev** [comment]
Correct - we haven't run into this error after implementing the new caching logic. Will close this.
