### ISSUE TITLE
Improve common/para/para_test.go logic

### ISSUE THREAD

**Issue by chayev** [gothamhq/gotham#8]
It looks like the test [here](https://github.com/gothamhq/gotham/blob/763db3edc9bdd6f0b6d0594bd1829e04e268a877/common/para/para_test.go#L86) could be improved. The number of workers seems to be set arbitrarily. 

We could improve the test by running the loop twice, once with 1 worker and once with the number of cores the machine has. If the latter is quicker than the former the test would pass.

**Comment by felicianotech** [comment]
This is an upstream issue. Closing.

https://github.com/gohugoio/hugo/issues/6963
